# Generated by Django 5.2.6 on 2026-10-07 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('senior_high', 'Senior high school'), ('college', 'College')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Use a numeric year or grade level, e.g. 1 or 11.')]),
        ),
    ]
